site_name: Learning Path
repo_url: https://github.com/jland-redhat/markdown-material.git
theme:
  name: material
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - Overview: "index.md"
  - Learning Paths By Persona:
    - SDET:
      - "Application Development in Containers (Quick Path) - Fancy": "app-dev-quick-fancy.md"
      - "Application Development in Containers (Quick Path) - Boring": "app-dev-quick-boring.md"