site_name: Learning Path
repo_url: https://github.com/jland-redhat/markdown-material.git
theme:
  name: material
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - app_development_containers_fancy.md